"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { QueryClientProvider, QueryClient } from '@tanstack/react-query'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const queryClient = new QueryClient()

  return (

    <html lang="en">
      <body className={inter.className}>

        <QueryClientProvider client={queryClient}>

          {children}

        </QueryClientProvider>

      </body>

    </html>
  )
}


// ;
// import {
//   Hydrate,
//   QueryClient,
//   QueryClientProvider,
// } from '@tanstack/react-query';
// //  import type { Metadata } from 'next'


// // import { Inter } from 'next/font/google'
// import './globals.css'

// // const inter = Inter({ subsets: ['latin'] })

// // export const metadata: Metadata = {
// //   title: 'Create Next App',
// //   description: 'Generated by create next app',
// // }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {


//   const queryClient = new QueryClient()

//   return (
//     <html lang="en">
//       <body>
//         <QueryClientProvider client={queryClient}>

//           {children}

//         </QueryClientProvider>

//       </body>
//     </html>
//   )
// }
